name: Deploy to GitHub pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          cd test/e2e
          npm ci
          npx playwright install --with-deps
          cd ..
          cd ..
          npm run e2e
        env:
          VITE_API_URL: 'test/api'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://git:${github_token}@github.com/${repository}.git
          npm run build
          cp dist/index.html dist/404.html
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"

        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.DEPLOY_SECRET }}
          repository: ${{ github.repository }}